services:
  app:
    image: hello-front-dev
    build:
      context: . 
      dockerfile: todo-frontend/dev.Dockerfile 
    volumes:
      - ./:/todo-frontend/usr/src/app 
    ports:
      - 3000:3000
    container_name: hello-whole 
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-whole
    depends_on:
      - app # wait for the frontend container to be started
